name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: UUIDV7 vs Foundation UUID (Throughput)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: sudo xcode-select -s /Applications/Xcode_26.2.app
      - name: Install Dependencies
        run: brew install jemalloc
      - name: Run Benchmark
        run: |
          cd Benchmarks
          swift package benchmark --target swift-uuidv7-benchmarks

  macos:
    name: macOS
    runs-on: macos-26
    strategy:
      matrix:
        xcode: ["26.2"]
        config: ["debug", "release"]
    steps:
      - uses: actions/checkout@v6
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run ${{ matrix.config }} tests
        run: swift test --configuration ${{ matrix.config }}

  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: ["debug", "release"]
    steps:
      - uses: actions/checkout@v6
      - name: "Test Swift Package on Linux"
        run: swift test --configuration ${{ matrix.config }}

  android:
    name: Android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: ["debug", "release"]
    steps:
      - uses: actions/checkout@v6
      - name: "Test Swift Package on Android"
        uses: swift-android-sdk/swift-android-action@v2
        with:
          swift-version: 6.2
          swift-configuration: ${{ matrix.config }}
          run-tests: false # NB: Emulator booting seems to be flakey
